### ISSUE TITLE
Plagiarism?

### ISSUE THREAD

**Issue by johnwwdcstudent** [wwdc/2017#7]
The third submission (https://github.com/kylespadaro/WWDC-2017) by Kyle Spadaro seems to be plagiarized from this repository: https://github.com/robin/2048_Playground by Lu Yibin. 

The Contents.swift file is very, very similar.
Spadaro: https://github.com/kylespadaro/WWDC-2017/blob/master/Contents.swift
Yibin: https://github.com/robin/2048_Playground/blob/master/2048.playground/Contents.swift

Both have 358 lines and the code looks almost exactly the same.

**Comment by johnwwdcstudent** [comment]
Archive links: 
- https://archive.today/ILPYI
- https://archive.today/VAvbo
- https://archive.today/ldPAK
- https://archive.today/9rPoL

**Comment by johnwwdcstudent** [comment]
@kylespadaro

**Comment by kylespadaro** [comment]
Sorry about that, I did respond to your DAM on Twitter. This was not plagiarized. However, I did download this playground before developing my own version to see how I would be able to make an entire version of 2048 into one Swift file.

**Comment by kylespadaro** [comment]
If you want to believe that I plagiarized it, I could just update the Swift file with completely different code so it doesn't look similar to the other playground.

**Comment by kylespadaro** [comment]
My full explanation of this is that it was merely a coincidence due to the unused code in the middle, so I could just remove that and the total number of lines would be around 336. I'm not saying that I haven't seen that plaground before, because I have. I just never copied anything from it.

I'm just going to add that you didn't need to reply to a decent number of my tweets with a link to this page. It was completely unnecessary and you could have just left it in the DMs.

**Comment by kylespadaro** [comment]
I'll edit the code before re-adding it to the playground so that it doesn't seem similar to Lu Yibin's code, which is actually very clever. I learned from his code in the past.

**Comment by kylespadaro** [comment]
With that being said, I'm going to close this issue. You are welcome to make a new one in the future if you would like to.

**Comment by johnwwdcstudent** [comment]
#MAGA #Trump2016

Thanks for the reply. By any chance, do you support Crooked Hillary?

Archives: Original: https://archive.fo/9rPoL - New: https://archive.fo/ldPAK

**Comment by johnwwdcstudent** [comment]
#Trump2020 #Trump2024 #Make #America #Great #Again

**Comment by kylespadaro** [comment]
Well I am a Republican so I support Trump. But I don't let my political beliefs get in the way of the rest of my life

**Comment by Schemetrical** [comment]
Any issue with plagiarism is not the responsibility of me nor the managers of the repo. Whether there is or not remains the decision of Apple. Thanks for your concern though.
